environments:
  # For each environment the env_name is required to make it.
  # Additional parameters (per environment) should be added after the env_name.
  # Example of additional parameter for CartPole Environment - render_mode: "rgb_array"
  cartpole:
    env_name: "CartPole-v1"
    episodes: 200

#  mountaincar:
#    env_name: "MountainCar-v0"
#    episodes: 250
#
#  acrobot:
#    env_name: "Acrobot-v1"
#    episodes: 500

parameters:
  learning_rate: 0.1
  batch_size: 64
  gamma: 0.9
